language: python
python:
    - "2.7"

sudo: required
        
branches:
    - master
    - develop

env:
    matrix:
        - PLATFORMIO_CI_SRC=examples/RGBLEDTest

install:
    - pip install -U platformio
    - platformio platform install -f infineonxmc 
    - platformio platform install -f atmelavr

script:
    - platformio ci --lib="." --board=xmc1100_boot_kit --board=xmc4700_relax_kit --board=uno
    
after_success:
   # only build once (after one job by checking id, however this does not work reliably)
    - |
      if [ $(($TRAVIS_JOB_ID - $TRAVIS_BUILD_ID)) -eq 2 ]; then
        export REPO_NAME=${TRAVIS_REPO_SLUG#*/}
        git clone https://github.com/Infineon/InfineonDoxyGenerator.git
        cd InfineonDoxyGenerator/docs
        chmod +x publish_pdf.sh
        ./publish_pdf.sh
      fi
